apiVersion: v1
kind: Service
metadata:
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
  name: notebook-controller-service
  namespace: kubeflow
spec:
  ports:
    - port: 443
      targetPort: 443
      name: https
    - port: 8081
      targetPort: 8081
      name: metrics
  selector:
    app: notebook-controller
    kustomize.component: notebook-controller
